version: 2
updates:
  - package-ecosystem: docker
    directory: /environment
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
  - package-ecosystem: docker
    directory: /environment/mcp-server
    schedule:
      interval: weekly
    labels:
      - dependencies
      - docker
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    labels:
      - dependencies
      - github-actions
